### ISSUE TITLE
Version 1.0.2 isn't submitted to Cocoapods repo

### ISSUE THREAD

**Issue by Miggets7** [ibnusina/ReactiveAFNetworking#1]
I need the fix for the delete request, but unfortunately the fix isn't pushed to Cocoapods repo

**Comment by ibnusina** [comment]
Thank you for reporting the issue. I have submitted version 1.0.2. Tell me whether your problem is fixed or not. If you have more issue please don't hesitate to make any report.

**Comment by Miggets7** [comment]
It's fixed now. Thank you and keep up the good work!
